# -*- coding: utf-8 -*-
"""Task3Code.ipyn

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XpqmA6PBgxeCC5b0vLPAgW2U_D1uNwJx
"""

import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
import os

def task3_clt():
    """
    Task 3: Central Limit Theorem (CLT) Simulation
    This script demonstrates how the sum of independent uniform variables
    converges to a Normal Distribution.
    """
    m = 1000  # Number of independent experiments
    n_values = [2, 5, 10, 30, 50]  # Values of n to test

    # Theoretical properties for Standard Uniform U[0,1]
    mu = 0.5
    sigma = np.sqrt(1/12)

    # Set up the plotting area (Histograms on left, Q-Q plots on right)
    fig, axes = plt.subplots(len(n_values), 2, figsize=(12, 18))

    for i, n in enumerate(n_values):
        # 1. Generate m independent experiments, each summing n variables
        samples = np.random.uniform(0, 1, (m, n))
        sums = np.sum(samples, axis=1)

        # 2. Standardize the sums using the formula: Zi = (Sn - n*mu) / (sigma * sqrt(n))
        standardized_sums = (sums - n * mu) / (sigma * np.sqrt(n))

        # 3. Plot the Histogram of standardized sums
        axes[i, 0].hist(standardized_sums, bins=30, density=True, alpha=0.6, color='skyblue', label=f'n={n}')

        # 4. Overlay the standard normal density function N(0,1)
        x = np.linspace(-4, 4, 100)
        axes[i, 0].plot(x, stats.norm.pdf(x, 0, 1), 'r-', lw=2, label='N(0,1)')
        axes[i, 0].set_title(f'Standardized Sums Histogram (n={n})')
        axes[i, 0].legend()

        # 5. Assess normality using Normal Q-Q plots
        stats.probplot(standardized_sums, dist="norm", plot=axes[i, 1])
        axes[i, 1].set_title(f'Normal Q-Q Plot (n={n})')

    plt.tight_layout()

    # Create directory if it doesn't exist to prevent FileNotFoundError
    output_dir = 'results/figures'
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    # Save and show
    plt.savefig(f'{output_dir}/clt_plots.png')
    print(f"Plot saved to {output_dir}/clt_plots.png")
    plt.show()

# FIXED: Corrected the dunder name check
if __name__ == "__main__":
    task3_clt()